networks:
  app_network:
    driver: bridge

services:
  fastapi-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/code/app
      - ./backend/.env:/code/.env  # Copiar .env al contenedor
    env_file:
      - ./backend/.env  # Cargar variables desde el archivo
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    ports:
      - "8000:80"
    networks:
      - app_network

  astro:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0 --port 4321"
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    networks:
      - app_network
    depends_on:
      - fastapi-app
    restart: unless-stopped