networks:
  app_network:
    driver: bridge

services:
  fastapi-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/code/app
    env_file:
      - ./backend/.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    ports:
      - "8000:80"  # Solo si quieres acceso externo
    networks:
      - app_network

  astro:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0 --port 4321"
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_network
